# #python# error1
[image:36821DFE-BEAB-4A8D-A91F-81BD46AF2642-2529-0001E892DAFA2850/FEFBF4F0-B0B1-4942-AEC9-612EB78BD522.png]

try:
	a
except NameError, e:
	print “catch Error:”, e

print “exec over”

[image:F2A3B804-9EEC-43DF-8C65-517F2B411C1D-38320-00025C0FCFCD1B47/66F973E7-E9D3-415F-9173-F0D8C23FD426.png]

[image:A1FCE5A7-5A90-4517-B70A-269072DDAADE-38320-00025C2ECB37156E/B5203C80-F7E2-460E-89C2-BE5E71DCF897.png]

[image:29FB1876-9E66-48A7-8E0A-8A488DA47BC7-38320-000260984994F452/97684ABB-354F-4FF5-A4AB-F25C5B0F101F.png]


[image:14E9C56A-11F6-4470-8A1F-E2D170DDA1AC-38320-0002606CA5E4CEAE/A6AF4411-9BDA-4A31-B3C2-42EFCBF8487F.png]